<?php

/**
 * @file
 * Contains leo_paragraphs_slider.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function leo_paragraphs_slider_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the leo_paragraphs_slider module.
    case 'help.page.leo_paragraphs_slider':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provide a custom “slider” paragraph type.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function leo_paragraphs_slider_theme() {
  return [
    'leo_paragraphs_slider' => [
      'render element' => 'children',
    ],
  ];
}
